spring:
  application:
    name: team-project

server:
  port: 8585
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    path: /docs/swagger
    enabled: true
    try-it-out-enabled: true
  api-docs:
    path: /api-docs
    enabled: true