spring:
  application:
    name: team-project
  datasource:
    url: jdbc:postgresql://dev_db:5432/dev_db
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8686
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    path: /api.test/docs/swagger
    enabled: true
    try-it-out-enabled: true
  api-docs:
    path: /api-docs
    enabled: true