
spring:
  application:
    name: team-project
  datasource:
    url: jdbc:postgresql://localhost:5432/local_db
    username: devuser
    password: devpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: 8585
  error:
    include-stacktrace: always
    include-message: always
    include-binding-errors: always

springdoc:
  swagger-ui:
    path: /api.local/docs/swagger
    enabled: true
    try-it-out-enabled: true
  api-docs:
    path: /api-docs
    enabled: true